/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CashFlowRouteImport } from './routes/cash-flow'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as CashFlowNewRouteImport } from './routes/cash-flow.new'
import { Route as CustomersNewRouteImport } from './routes/customers.new'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as OrdersNewRouteImport } from './routes/orders.new'
import { Route as ProductsNewRouteImport } from './routes/products.new'
import { Route as ApiOrdersIdDotpdfRouteImport } from './routes/api/orders/$id[.]pdf'
import { Route as OrdersIdReceiptRouteImport } from './routes/orders.$id.receipt'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CashFlowRoute = CashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const CashFlowNewRoute = CashFlowNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CashFlowRoute,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CustomersRoute,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OrdersRoute,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProductsRoute,
} as any)
const ApiOrdersIdDotpdfRoute = ApiOrdersIdDotpdfRouteImport.update({
  id: '/api/orders/$id.pdf',
  path: '/api/orders/$id.pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdReceiptRoute = OrdersIdReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => OrdersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cash-flow': typeof CashFlowRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/cash-flow/new': typeof CashFlowNewRoute
  '/customers/new': typeof CustomersNewRoute
  '/orders/$id': typeof OrdersIdRouteWithChildren
  '/orders/new': typeof OrdersNewRoute
  '/products/new': typeof ProductsNewRoute
  '/api/orders/$id.pdf': typeof ApiOrdersIdDotpdfRoute
  '/orders/$id/receipt': typeof OrdersIdReceiptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cash-flow': typeof CashFlowRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/cash-flow/new': typeof CashFlowNewRoute
  '/customers/new': typeof CustomersNewRoute
  '/orders/$id': typeof OrdersIdRouteWithChildren
  '/orders/new': typeof OrdersNewRoute
  '/products/new': typeof ProductsNewRoute
  '/api/orders/$id.pdf': typeof ApiOrdersIdDotpdfRoute
  '/orders/$id/receipt': typeof OrdersIdReceiptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cash-flow': typeof CashFlowRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/cash-flow/new': typeof CashFlowNewRoute
  '/customers/new': typeof CustomersNewRoute
  '/orders/$id': typeof OrdersIdRouteWithChildren
  '/orders/new': typeof OrdersNewRoute
  '/products/new': typeof ProductsNewRoute
  '/api/orders/$id.pdf': typeof ApiOrdersIdDotpdfRoute
  '/orders/$id/receipt': typeof OrdersIdReceiptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cash-flow'
    | '/customers'
    | '/dashboard'
    | '/login'
    | '/orders'
    | '/products'
    | '/reports'
    | '/cash-flow/new'
    | '/customers/new'
    | '/orders/$id'
    | '/orders/new'
    | '/products/new'
    | '/api/orders/$id.pdf'
    | '/orders/$id/receipt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cash-flow'
    | '/customers'
    | '/dashboard'
    | '/login'
    | '/orders'
    | '/products'
    | '/reports'
    | '/cash-flow/new'
    | '/customers/new'
    | '/orders/$id'
    | '/orders/new'
    | '/products/new'
    | '/api/orders/$id.pdf'
    | '/orders/$id/receipt'
  id:
    | '__root__'
    | '/'
    | '/cash-flow'
    | '/customers'
    | '/dashboard'
    | '/login'
    | '/orders'
    | '/products'
    | '/reports'
    | '/cash-flow/new'
    | '/customers/new'
    | '/orders/$id'
    | '/orders/new'
    | '/products/new'
    | '/api/orders/$id.pdf'
    | '/orders/$id/receipt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CashFlowRoute: typeof CashFlowRouteWithChildren
  CustomersRoute: typeof CustomersRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  ApiOrdersIdDotpdfRoute: typeof ApiOrdersIdDotpdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-flow': {
      id: '/cash-flow'
      path: '/cash-flow'
      fullPath: '/cash-flow'
      preLoaderRoute: typeof CashFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-flow/new': {
      id: '/cash-flow/new'
      path: '/new'
      fullPath: '/cash-flow/new'
      preLoaderRoute: typeof CashFlowNewRouteImport
      parentRoute: typeof CashFlowRoute
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/orders/new': {
      id: '/orders/new'
      path: '/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/products/new': {
      id: '/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/api/orders/$id.pdf': {
      id: '/api/orders/$id.pdf'
      path: '/api/orders/$id.pdf'
      fullPath: '/api/orders/$id.pdf'
      preLoaderRoute: typeof ApiOrdersIdDotpdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id/receipt': {
      id: '/orders/$id/receipt'
      path: '/receipt'
      fullPath: '/orders/$id/receipt'
      preLoaderRoute: typeof OrdersIdReceiptRouteImport
      parentRoute: typeof OrdersIdRoute
    }
  }
}

interface CashFlowRouteChildren {
  CashFlowNewRoute: typeof CashFlowNewRoute
}

const CashFlowRouteChildren: CashFlowRouteChildren = {
  CashFlowNewRoute: CashFlowNewRoute,
}

const CashFlowRouteWithChildren = CashFlowRoute._addFileChildren(
  CashFlowRouteChildren,
)

interface CustomersRouteChildren {
  CustomersNewRoute: typeof CustomersNewRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersNewRoute: CustomersNewRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface OrdersIdRouteChildren {
  OrdersIdReceiptRoute: typeof OrdersIdReceiptRoute
}

const OrdersIdRouteChildren: OrdersIdRouteChildren = {
  OrdersIdReceiptRoute: OrdersIdReceiptRoute,
}

const OrdersIdRouteWithChildren = OrdersIdRoute._addFileChildren(
  OrdersIdRouteChildren,
)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRouteWithChildren
  OrdersNewRoute: typeof OrdersNewRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRouteWithChildren,
  OrdersNewRoute: OrdersNewRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface ProductsRouteChildren {
  ProductsNewRoute: typeof ProductsNewRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsNewRoute: ProductsNewRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CashFlowRoute: CashFlowRouteWithChildren,
  CustomersRoute: CustomersRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  ApiOrdersIdDotpdfRoute: ApiOrdersIdDotpdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
